### ISSUE TITLE
500 error in tests

### ISSUE THREAD

**Issue by ObaydaAlesawi** [mbpcoder/laravel-api-versioning#2]
I have installed the latest package version, but I got this error when trying to do a test on v2 that does not exist and v1 is exist

![image](https://user-images.githubusercontent.com/32073999/147477128-4e206923-b480-4a8a-b191-93dcc747f99d.png)
I guess the issue is with the binding

**Comment by ObaydaAlesawi** [comment]
@mbpcoder have any updates here?

**Comment by mbpcoder** [comment]
> @mbpcoder have any updates here?

What is your Laravel version?
